### ISSUE TITLE
Deploy Helix on dev server and write document

### ISSUE THREAD

**Issue by Akagi201** [lu-bann/helix#3]

**Comment by zsluedem** [comment]
I think I started helix like a month ago and it is still running.

FYI, here is the config.

```yml
postgres:
  hostname: 127.0.0.1
  port: 5432
  db_name: template1
  user: postgres
  password: 12345678
  region: 0
  region_name: ''
redis:
  url: redis://localhost:6379
broadcasters:
- !BeaconClient
  url: http://localhost:4000
simulator:
  url: http://localhost:8080
beacon_clients:
- url: http://localhost:4000
relays: []
network_config: !Custom
  dir_path: /root/luban/network-configs/config.yaml
  genesis_validator_root: '0x0000000000000000000000000000000000000000000000000000000000000000'
  genesis_time: 1718967600
logging: !Console
validator_preferences:
  filtering: regional
  trusted_builders: null
  header_delay: true
router_config:
  enabled_routes:
  - route: GetValidators
    rate_limit: null
  - route: SubmitBlock
    rate_limit: null
  - route: SubmitBlockOptimistic
    rate_limit: null
  - route: ValidatorRegistration
    rate_limit: null
  - route: GetHeader
    rate_limit:
      limit_duration_ms: 12
      max_requests: 3
  - route: GetPayload
    rate_limit: null
  - route: ProposerPayloadDelivered
    rate_limit: null
  - route: RegisterValidators
    rate_limit: null
  - route: Status
    rate_limit: null
target_get_payload_propagation_duration_ms: 0
```
